services:
  db:
    image: postgres:17
    container_name: local-announcements-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - local_announcements_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  local_announcements_db: